# Infrastructure Setup Configuration
# Kubernetes and Docker Compose configurations for deployment

apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: workflow-automation
data:
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "admin"
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  WEBHOOK_URL: "https://n8n.example.com/"
  GENERIC_TIMEZONE: "UTC"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres-service"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_PORT: "5432"
  EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
  EXECUTIONS_DATA_SAVE_ON_SUCCESS: "all"
  EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-workflow
  namespace: workflow-automation
spec:
  serviceName: n8n-service
  replicas: 2
  selector:
    matchLabels:
      app: n8n-workflow
  template:
    metadata:
      labels:
        app: n8n-workflow
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
          name: http
        envFrom:
        - configMapRef:
            name: n8n-config
        env:
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: db-user
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: db-password
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: workflow-automation
spec:
  selector:
    app: n8n-workflow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: n8n-autoscaler
  namespace: workflow-automation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: n8n-workflow
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

